### ISSUE TITLE
why not start nova in CAIO vm?[solved]

### ISSUE THREAD

**Issue by Daqu** [Crystal-SDS/Crystal-Controller#1]
there is always a error message every time I login, and I can't get the information of system monitoring.
it seems that stopping nova service causes the problem, because the console gets tips like below:

> Call to list supported extensions failed. This is likely due to a problem communicating with the Nova endpoint. Host Aggregates panel will not be displayed.
[18/Jul/2017 09:40:47] "GET /sdscontroller/storagemonitoring/system HTTP/1.1" 200 22127
[18/Jul/2017 09:40:47] "GET /i18n/js/horizon+openstack_dashboard/ HTTP/1.1" 200 2486

could you give some command sets to solve this little trouble? : )

**Comment by gerardparis** [comment]
Hi @Daqu ,

There are 2 different and not-related issues here:
1. Nova service is disabled in the VM because Crystal doesn't need Nova. The only inconveniences are these warning messages in SDS-Dashboard.
2. System monitoring panel is not working because we are transitioning from collectd to metricbeat for system metrics, but unfortunately the VM is not up to date. To solve this second issue, you should stop collectd, install metricbeat and make a slight change in SDS-Dashboard:

**Stop collectd**
sudo /etc/init.d/collectd stop

**Install metricbeat**
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
sudo apt-get install apt-transport-https
sudo apt-get update && sudo apt-get install metricbeat
sudo update-rc.d metricbeat defaults 95 10
sudo /etc/init.d/metricbeat start
sudo /usr/share/metricbeat/scripts/import_dashboards

**Configure metricbeat dashboard**
In SDS Dashboard, open SDS Controller -> Data Exploration -> Exploration. This should open kibana. In Management  -> Saved objects -> Dashboards, you'll find a dashboard named "Metricbeat System overview". Open this dashboard (view) and go to the "Share menu" in the top bar. Under "Share Snapshot", in "Embedded iframe", copy the short URL (only the alphanumeric string).
Edit /home/crystal/crystal/SDS-Dashboard/openstack_dashboard/local/local_settings.py and change the following variable with the copied alphanumeric string:
`IOSTACK_MONITORING_SYSTEM_PLOT = "xxxxxxxxxxxx"`

Hope this helps!

**Comment by Daqu** [comment]
ok, it works. I can see the information of system monitoring. But the command
`sudo /usr/share/metricbeat/scripts/import_dashboards`
seems works after finishing crystal's or kibana's start-up. And the short URL I copied is same with the one of  local_settings.py.
anyway, it works! thank you! 👍

**Comment by gerardparis** [comment]
Right. You need to enable Elastic Stack (Logstash, Elasticsearch, Kibana) before importing Metricbeat dashboards.
